main_app/urls.py
from django.urls import path, include
from . import views 
from .views import RestaurantListView, DestinationListView, DestinationDetailView, add_restaurant, EditDestinationView, EditRestaurantView, DeleteDestinationView, DeleteRestaurantView, LandingPageView, AboutView

urlpatterns = [
        path('platepick/about', AboutView.as_view(), name='about'),
        path('', views.LandingPageView.as_view(), name='Landing-Page'),
        path('platepick/create/', views.DestinationCreate.as_view(), name='platepick-create'), 
        path('platepick/restaurants/', RestaurantListView.as_view(), name='restaurant-list'),
        path('platepick/destinations/', DestinationListView.as_view(), name='destination-list'),
        path('platepick/destinations/<int:pk>/', DestinationDetailView.as_view(), name='platepick-detail'),
        path('platepick/destinations/<int:pk>/add-restaurant/', add_restaurant, name='add-restaurant'),
        path('platepick/destinations/<int:pk>/edit/', EditDestinationView.as_view(), name='edit-destination'),
        path('platepick/restaurants/<int:pk>/edit/', EditRestaurantView.as_view(), name='edit-restaurant'),
        path('platepick/destinations/<int:pk>/delete/', DeleteDestinationView.as_view(), name='delete-destination'),
        path('platepick/restaurants/<int:pk>/delete/', DeleteRestaurantView.as_view(), name='delete-restaurant'),
        path('accounts/signup/', views.signup, name='signup'),
]

platepick/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

class Destination(models.Model):
    country = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.city}, {self.state}, {self.country}"

    def get_absolute_url(self):
        return reverse('platepick-detail', kwargs={'pk': self.pk})

class Restaurant(models.Model):
    name = models.CharField(max_length=100)
    cuisine = models.CharField(max_length=100)
    price_option = [
        ('option1', '$'),
        ('option2', '$$'),
        ('option3', '$$$'),
        ('option4', '$$$$'),
        ('option5', '$$$$$')
    ]
    visit_option = [
        ('option1', 'Want to Try'),
        ('option2', 'Visited')
    ]
    price = models.CharField(max_length=15, choices=price_option, default='$')
    visit = models.CharField(max_length=15, choices=visit_option, default='option1')
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE, default=1, related_name="restaurants")

    def __str__(self):
        return f"{self.get_name_display()} on {self.date}" # might not need this

main_app/forms.py
# will i end up needing this page?

from django import forms
from .models import Restaurant

class RestaurantForm(forms.ModelForm):
    class Meta:
        model = Restaurant
        fields = ['name', 'cuisine', 'price', 'visit']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Destination
from .models import Restaurant
from .restaurantForm import RestaurantForm
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import UpdateView, DeleteView, TemplateView
from django.contrib.auth.views import LoginView

def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('destination-list')
        else:
            error_message = 'Invalid sign up - try again'
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'signup.html', context)


class DestinationCreate(LoginRequiredMixin, CreateView):
    model = Destination
    fields = ['country', 'state', 'city']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)
    sucess_url = '/platepick/'

class RestaurantListView(LoginRequiredMixin, ListView):
    model = Restaurant
    template_name = 'restaurants/restaurantIndex.html'  
    context_object_name = 'restaurants'  
    ordering = ['name']  

class DestinationListView(LoginRequiredMixin, ListView):
    model = Destination
    template_name = 'destinations/destination_restaurantlists.html'
    context_object_name = 'destinations'

    def get_queryset(self):
        return Destination.objects.filter(user=self.request.user)

class DestinationDetailView(LoginRequiredMixin, DetailView):
    model = Destination
    template_name = 'destinations/destination_details.html'
    context_object_name = 'destination'


@login_required
def add_restaurant(request, pk):
    destination = get_object_or_404(Destination, pk=pk)  

    if request.method == 'POST':
        form = RestaurantForm(request.POST)  
        if form.is_valid():
            restaurant = form.save(commit=False)  
            restaurant.destination = destination  
            restaurant.save()  
            return redirect('platepick-detail', pk=pk)  
    else:
        form = RestaurantForm()  

    return render(request, 'restaurants/add_restaurant.html', {'form': form, 'destination': destination})

class EditDestinationView(LoginRequiredMixin, UpdateView):
    model = Destination
    fields = ['country', 'state', 'city']
    template_name = 'destinations/edit_destination.html'
    
    def get_success_url(self):
        return reverse_lazy('platepick-detail', kwargs={'pk': self.object.pk})

class EditRestaurantView(LoginRequiredMixin, UpdateView):
    model = Restaurant
    form_class = RestaurantForm  
    template_name = 'restaurants/edit_restaurant.html'

    def get_success_url(self):
        return reverse_lazy('platepick-detail', kwargs={'pk': self.object.destination.pk})

class DeleteDestinationView(LoginRequiredMixin, DeleteView):
    model = Destination
    template_name = 'destinations/destination_confirm_delete.html'
    success_url = reverse_lazy('destination-list')

class DeleteRestaurantView(LoginRequiredMixin, DeleteView):
    model = Restaurant
    template_name = 'restaurants/restaurant_confirm_delete.html'

    def get_success_url(self):
        return reverse_lazy('platepick-detail', kwargs={'pk': self.object.destination.pk})

class LandingPageView(LoginView):
    template_name = 'landing_page.html'

class AboutView(TemplateView):
    template_name = "about.html"

main_app/templates/about.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block navigation %}
{% if user.is_authenticated %}
    <li><a href="{% url 'platepick-create' %}">Add a Destination</a></li>
    <li><a href="{% url 'destination-list' %}">Destinations</a></li>
{% else %}
    <li><a href="{% url 'Landing-Page' %}">Login</a></li>
    <li><a href="{% url 'signup' %}">Sign Up</a></li>
{% endif %}
{% endblock %}
{% block content %}
<div class="page-header">
  <h1>Welcome to PlatePick</h1>
  <p>Your Personal Guide to Culinary Adventures</p>
  <p>PlatePicks is the ultimate platform for food lovers to organize their dining experiences. Whether you're planning your next foodie adventure or reminiscing about past restaurant visits, PlatePicks makes it easy to add, manage, and track your favorite spots. Save restaurants you've discovered, rate and review the ones you've visited, and build a personalized dining wish list—all in one convenient place. With PlatePicks, every meal is a story waiting to be told!</p>
</div>
{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="shortcut icon" type="image/png" href="" />
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <title>Plate Pick!</title>
    {% block head %} 
    {% endblock %}
    </head>
    <body>
    <header>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                {% block navigation %}
                <li><a href="{% url 'platepick-create' %}">Add a Destination</a></li>
                {% endblock %}

                {% block home %}
                <li><a href="{% url 'Landing-Page' %}">Back to Home Page</a></li>
                <li>
                    <form id="logout-form" method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit">Log out</button>
                    </form>
                </li>
                {% endblock %}
                {% else %}
                {% block about %}
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'Landing-Page' %}">Login</a></li>
                <li><a href="{% url 'signup' %}">Sign Up</a></li>
                {% endblock %}
                {% endif %}
            </ul>
        </nav>
    </header>
    <main>
        {% block content %} 
        {% endblock %}
        </main>
    </body>
</html>
    

main_app/templates/destinations/delete_destination.html
{% extends 'base.html' %}  
{% load static %} 
{% block content %}

<div class="page-header">
  <h1>Delete This Destination?</h1>
  <img src="{% static '' %}" alt="" />
</div>

<h2>Are you sure you want to delete this {{ object.city }}?</h2>

<form action="" method="post" class="form">
  {% csrf_token %}
  <a href="{% url 'platepick-detail' object.id %}" class="btn secondary">Cancel</a>
  <button type="submit" class="btn danger">Yes - Garbage!</button>
</form>

{% endblock %}

main_app/templates/destinations/destination_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-header">
        <h1>Delete Destination</h1>
        <p>Are you sure you want to delete "{{ object.city }}, {{ object.state }}, {{ object.country }}" from your destinations?</p>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn delete">🗑️ Yes- Delete!</button>
            <a href="{% url 'platepick-detail' pk=object.pk %}" class="btn cancel">Cancel</a>
        </form>
    </div>
{% endblock %}

main_app/templates/destinations/destination_details.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/DestinationDetail.css' %}" />
{% endblock %} 
{% block content %}
    <div class="page-header">
        <h1>{{ destination.city }} - Restaurants</h1>
    </div>
    <ul>
        {% for restaurant in destination.restaurants.all %}
            <li>
                <strong>{{ restaurant.name }}</strong> - {{ restaurant.cuisine }} <br>
                Price: {{ restaurant.get_price_display }} | Status: {{ restaurant.get_visit_display }}
                <a href="{% url 'edit-restaurant' pk=restaurant.pk %}">✏️ Edit</a>
                <a href="{% url 'delete-restaurant' pk=restaurant.pk %}" class="btn delete">🗑️ Delete</a>
            </li>
        {% empty %}
        <li>No restaurants found for this destination.</li>
      {% endfor %}
    </ul>
    <div class="links">
        <a href="{% url 'destination-list' %}">Back to Destinations</a>
        <a href="{% url 'add-restaurant' pk=destination.pk %}">➕ Add a Restaurant</a>
        <a href="{% url 'edit-destination' pk=destination.pk %}">✏️ Edit Destination</a>
        <a href="{% url 'delete-destination' pk=destination.pk %}" class="btn delete">🗑️ Delete Destination</a>
    </div>
{% endblock %}

main_app/templates/destinations/destination_restaurantlists.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/DestinationIndex.css' %}" />
{% endblock %} 
{% block content %}
    <div class="page-header">
        <h1>Destinations</h1>
    </div>
    <ul>
        {% for destination in destinations %}
            <li>
                <a href="{% url 'platepick-detail' destination.pk %}">{{ destination.city }}</a>
            </li>
        {% empty %}
            <li>No destinations available.</li>
        {% endfor %}
    </ul>
{% endblock %}

main_app/templates/destinations/edit_destination.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/editDestination.css' %}" />
{% endblock %} 
{% block content %}
    <div class="page-header">
        <h1>Edit Destination {{ destination.city }}</h1>
    </div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    <div class = "cancel">
        <a href="{% url 'platepick-detail' pk=object.pk %}">Cancel</a>
    </div>
{% endblock %}

main_app/templates/landing_page.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/base.css' %}" />
{% endblock %} 
{% block navigation %}
<li><a href="{% url 'about' %}">About</a></li>
{% if user.is_authenticated %}
    <li><a href="{% url 'destination-list' %}">Destinations</a></li>
    <li>
        <form id="logout-form" method="post" action="{% url 'logout' %}">
            {% csrf_token %}
            <button type="submit">Log out</button>
        </form>
    </li>
{% else %}
    <li><a href="{% url 'signup' %}">Sign Up</a></li>
    <li><a href="{% url 'Landing-Page' %}">Login</a></li>
{% endif %}
{% endblock %}
{% block content %}
<div class="page-header">
  <h1>Welcome to PlatePicks</h1>
  <p>Your Personal Guide to Culinary Adventures</p>
</div>
{% if not user.is_authenticated %}
<section>
  <form action="{% url 'Landing-Page' %}" method="post" class="login">
    <h1>Login</h1>
    {% csrf_token %} {{ form.as_p }}
    <input type="hidden" name="next" value="{{ next }}" />
    <button type="submit" class="btn submit">Login</button>
  </form>
</section>
{% endif %}
{% endblock %}

main_app/templates/main_app/destination_form.html
{% extends 'base.html' %} 
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
<div class="page-header">
  <h1>Add a Destination</h1>
</div>
<form action="" method="post" class="form-container">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <button type="submit" class="btn submit">Submit!</button>
</form>
{% endblock %}

main_app/templates/restaurants/add_restaurant.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/addRestaurant.css' %}" />
{% endblock %} 
{% block content %}
    <div class="page-header">
        <h1>Add a Restaurant to {{ destination.city }}</h1>
    </div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Restaurant</button>
    </form>
        <div class = "cancel">
            <a href="{% url 'platepick-detail' pk=destination.pk %}">Cancel</a>
        </div>
        {% if destination and destination.pk %}
            <a href="{% url 'platepick-detail' pk=destination.pk %}">Back to Destination</a>
        {% else %}
            <a href="{% url 'platepick-list' %}">Back to Destinations</a>
{% endif %}
{% endblock %}

main_app/templates/restaurants/confirm_delete_restaurant.html
{% extends 'base.html' %}
{% load staic %}
{% block content %}

<div class="'page-header">
    <h1>Delete {{ restaurant.name }}?</h1>
    <h2>Are you sure you want to dleete this restaurant?</h2>
</div>

<form methon="'POST">
    {% csrf_token %}
    <a href="{% rul 'platepick-detail pk=restaurant.destination.pk %}" class="btn secondary">Cancel</a>
    <button type="submit" class="btn, danger">Yes, Delete 🚮</button>
</form>

{% endblock%}

main_app/templates/restaurants/delete_restaurant.html
{% extends 'base.html' %}
{% load static %} 
{% block content %}

<div class="page-header">
    <h1>Delete This Restaurant?</h1>
    <img src="{% static '' %}" alt="" />
  </div>

    <h2>Are you sure you want to delete {{ object.name }}?</h2>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Yes, Delete!</button>
        <a href="{% url 'restaurant-list' %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/restaurants/edit_restaurant.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/editRestaurant.css' %}" />
{% endblock %} 
{% block content %}
    <div class="page-header">
        <h1>Edit Restaurant</h1>
    </div>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Save Changes</button>
    </form>
    <div class="cancel">
        <a href="{% url 'platepick-detail' pk=object.destination.pk %}">Cancel</a>
    </div>
{% endblock %}

main_app/templates/restaurants/restaurantIndex.html
{% extends 'base.html' %}
{% load static %} 
{% block head %}
<link rel="stylesheet" href="{% static 'css/form.css' %}" />
{% endblock %} 
{% block content %}
    <div class="page-header">
        <h1>Restaurants</h1>
    </div>
    <ul>
        {% for restaurant in restaurants %}
            <li>
                <strong>{{ restaurant.name }}</strong> - {{ restaurant.cuisine }} <br>
                Price: {{ restaurant.get_price_display }} | Status: {{ restaurant.get_visit_display }}
            </li>
        {% empty %}
            <li>No restaurants available in this city.</li>
        {% endfor %}
    </ul>
{% endblock %}

main_app/templates/restaurants/restaurant_confirm_delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="page-header">
        <h1>Delete Restaurant</h1>
        <p>Are you sure you want to delete "<strong>{{ object.name }}</strong>" from {{ object.destination.city }}?</p>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn delete">🗑️ Yes - Delete!</button>
            <a href="{% url 'platepick-detail' pk=object.destination.pk %}" class="btn cancel">Cancel</a>
        </form>
    </div>
{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %} 
{% load static %} 

{% block head %}
<link rel="stylesheet" href="{% static 'css/signup.css' %}" />
{% endblock %} 

{% block content %}
<div class="page-header">
  <h1>Sign Up to start Your PlatePick Journey!</h1>


{% if error_message %}
  <p class="red-text">{{ error_message }}</p>
{% endif %}
  <form action="" method="post" class="form-container" autocomplete="off">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <button type="submit" class="btn submit">Submit!</button>
  </form>
</div>
{% endblock %}